##
# Ansible playbook setting up developer tools used in building Training Wheels
#

---
- hosts: all
  gather_facts: False

  tasks:
    ##
    # Install compass and animation gems for theming
    #
    - name: Development | Install rubygems package
      action: apt pkg=rubygems state=installed

    - name: Development | Install Aurora
      action: command gem install compass-aurora creates=/var/lib/gems/1.8/specifications/compass-aurora-1.1.1.gemspec

    - name: Development | Install Animation
      action: command gem install animation --pre creates=/var/lib/gems/1.8/specifications/animation-0.1.alpha.3.gemspec

    ##
    # Configuration for accessing the classroom server (if required).
    # This IP address must match the IP specified in the classroom VagrantFile.
    #
    - name: Training Wheels | Set up some hosts entries so we can connect to the classroom server if required
      action: lineinfile regexp=.* insertafter=EOF dest=/etc/hosts line="10.1.0.3 remote.classroom sshcourse.remote.classroom instructor.sshcourse.remote.classroom jenny.sshcourse.remote.classroom harry.sshcourse.remote.classroom"

    ##
    # Node.js install.
    #
    - name: Node.js | Package prerequisites for node.js
      action: apt pkg=python-software-properties state=installed

    - name: Node.js | Add the node.js PPA
      action: command add-apt-repository -y ppa:chris-lea/node.js creates=/etc/apt/sources.list.d/chris-lea-node_js-precise.list

    - name: Node.js | Update the apt cache for the new repository
      action: apt update-cache=yes

    - name: Node.js | Install nodejs and npm
      action: apt pkg=$item state=installed
      with_items:
        - nodejs
        - npm

    - name: Node.js | Install grunt
      action: command npm install -g grunt creates=/usr/bin/grunt

    - name: Node.js | Install TW dev environment
      action: command npm install chdir=$twdir/controller/web
